/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./views/**/*.ejs"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline": "#74777d",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#004d67",
                "on-tertiary-fixed-variant": "#3f484d",
                "primary-container": "#0f1c2c",
                "tertiary-fixed-dim": "#bfc8ce",
                "surface-dim": "#c9dbfb",
                "on-error-container": "#93000a",
                "inverse-primary": "#bac8dc",
                "on-primary-fixed": "#0f1c2c",
                "error-container": "#ffdad6",
                "on-primary-container": "#778598",
                "secondary": "#006688",
                "secondary-container": "#76d1ff",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#3a4859",
                "on-secondary-fixed": "#001e2b",
                "on-surface": "#091c34",
                "surface-container-high": "#dee9ff",
                "on-secondary-container": "#005978",
                "primary-fixed": "#d6e4f9",
                "background": "#f9f9ff",
                "surface": "#f9f9ff",
                "secondary-fixed-dim": "#76d1ff",
                "surface-container-low": "#f0f3ff",
                "surface-variant": "#d5e3ff",
                "primary-fixed-dim": "#bac8dc",
                "secondary-fixed": "#c2e8ff",
                "on-tertiary-container": "#7c858b",
                "tertiary-fixed": "#dbe4ea",
                "outline-variant": "#c4c6cc",
                "inverse-surface": "#20314a",
                "error": "#ba1a1a",
                "tertiary-container": "#141d21",
                "on-background": "#091c34",
                "surface-tint": "#525f71",
                "on-surface-variant": "#44474c",
                "on-primary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-bright": "#f9f9ff",
                "tertiary": "#000000",
                "surface-container-highest": "#d5e3ff",
                "primary": "#000000",
                "on-tertiary-fixed": "#141d21",
                "inverse-on-surface": "#ebf1ff",
                "surface-container": "#e7eeff",
                "surface-container-lowest": "#ffffff"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "container-max": "1280px",
                "margin-desktop": "40px",
                "unit": "8px",
                "gutter": "24px",
                "margin-mobile": "20px"
            },
            fontFamily: {
                "body-md": ["Manrope", "sans-serif"],
                "label-md": ["Manrope", "sans-serif"],
                "body-sm": ["Manrope", "sans-serif"],
                "headline-sm": ["Manrope", "sans-serif"],
                "headline-xl": ["Manrope", "sans-serif"],
                "headline-md": ["Manrope", "sans-serif"],
                "body-lg": ["Manrope", "sans-serif"],
                "label-sm": ["Manrope", "sans-serif"],
                "headline-lg": ["Manrope", "sans-serif"],
                "sans": ["Manrope", "sans-serif"]
            },
            fontSize: {
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
            }
        },
    },
    plugins: [],
}
